### ISSUE TITLE
UBA stopped updating data

### ISSUE THREAD

**Issue by azrdev** [vied12/nsfw#21]
The website states 
> We are sorry to announce that we stopped to update the data because of the last UBA website update which removes the API we were using.

Have you asked UBA to bring the API back, what did they answer? How can we urge them to do so, e.g. by having a lot of opendata people ask them for it?

**Comment by vied12** [comment]
I didn't try to reach them. Because I have no hope this would change anything :confused:

**Comment by azrdev** [comment]
@vied12 please excuse if I'm too naive here, but looking at my browsers debug console on their page [0] yields some URLs which look like the API we'd be after: <https://www.umweltbundesamt.de/js/uaq/data/stations/limits> and <https://www.umweltbundesamt.de/js/uaq/data/transgressions/data?uaq_pollutant=PM10&uaq_transgressions_year=2017>.

Is this the API the nsfw code is using, have they just moved it?
Or did it change in structure, and if so, what do you think of adding to the announcement that we're happy to accept peoples' adaptations of the nsfw code to the new API?

[0] <https://www.umweltbundesamt.de/daten/luftbelastung/aktuelle-luftdaten#/stations>

**Comment by vied12** [comment]
Hi
You're right, this is the new API. I already quickly checked it and noticed there is no header or hint that tells us what is each value. There is probably a way to guess, by cross checking what appears on the web site, but this could change anytime, and this wouldn't be stable enough for smogalarm.
We already asked UBA for documentation about this API. Let's wait for what they answer. If they do... Otherwise we would have to guess our self or to find another source.
Thank you for your interest, this helps a lot !

**Comment by vied12** [comment]
You made me want to dig a little deeper and I found a nice endpoint with all the parameters I need (https://www.umweltbundesamt.de/uaq/csv/stations/data?station[]=&pollutant[]=NO2&scope[]=1SMW_MAX&group[]=pollutant&range[]=1494626400,1494712800). That was all I needed to fix smogalarm ! We are back :sunglasses: 
Thanks for the help !

**Comment by azrdev** [comment]
so cool, thank you!
